# Generated by Django 4.0.8 on 2022-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='images',
            field=models.FileField(null=True, upload_to='upload/property_images'),
        ),
    ]
