# Generated by Django 4.0.8 on 2022-12-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_properties_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
