# Generated by Django 4.0.8 on 2023-01-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
    ]
