# Generated by Django 4.0.8 on 2022-12-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_agent_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('size', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bedroom', models.IntegerField(default=0)),
                ('garage', models.IntegerField(default=0)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('images_1', models.ImageField(null=True, upload_to='upload/property_images')),
                ('images_2', models.ImageField(null=True, upload_to='upload/property_images')),
                ('images_3', models.ImageField(null=True, upload_to='upload/property_images')),
                ('images_4', models.ImageField(null=True, upload_to='upload/property_images')),
                ('images_5', models.ImageField(null=True, upload_to='upload/property_images')),
                ('description', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.agent')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.location')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
    ]
