# Generated by Django 4.0.8 on 2023-01-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230131_1229'),
    ]

    operations = [
    ]
