# Generated by Django 4.0.8 on 2023-02-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_property_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='imageFive',
            field=models.ImageField(blank=True, null=True, upload_to='upload/property_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imageFour',
            field=models.ImageField(blank=True, null=True, upload_to='upload/property_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imageOne',
            field=models.ImageField(blank=True, null=True, upload_to='upload/property_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imageThree',
            field=models.ImageField(blank=True, null=True, upload_to='upload/property_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imageTwo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/property_images'),
        ),
    ]
