# Generated by Django 4.0.8 on 2022-12-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_property_agarden_property_alarm_security_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='agarden',
            new_name='garden',
        ),
    ]
