# Generated by Django 4.0.8 on 2022-12-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_agarden_property_garden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='images_1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='images_2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='images_3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='images_4',
            new_name='image4',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='images_5',
            new_name='image5',
        ),
    ]
