# Generated by Django 4.0.8 on 2022-12-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_images_1_property_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image1',
            new_name='imageFive',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image2',
            new_name='imageFour',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image3',
            new_name='imageOne',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image4',
            new_name='imageThree',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image5',
            new_name='imageTwo',
        ),
    ]
