# Generated by Django 4.0.8 on 2022-12-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_image1_property_imagefive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(null=True, upload_to='agents'),
        ),
    ]
