# Generated by Django 4.0.8 on 2022-12-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_agent_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='swiming_pool',
            new_name='swimming_pool',
        ),
    ]
