# Generated by Django 4.0.8 on 2022-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_swiming_pool_property_swimming_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='school',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
