# Generated by Django 4.0.8 on 2022-12-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_location_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='mapLink',
            field=models.URLField(max_length=10000, null=True),
        ),
    ]
