# Generated by Django 4.0.8 on 2022-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_location_maplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='mapLink',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
