# Generated by Django 4.0.8 on 2022-12-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_propertycategory_property_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertycategory',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
