# Generated by Django 4.0.8 on 2023-01-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_blog_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
