# Generated by Django 4.0.8 on 2023-01-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_property_propertycategory_and_more'),
        ('base', '0019_rename_imageone_blog_image_alter_blog_body_and_more'),
    ]

    operations = [
    ]
